# COPTs are so all *.[ch] can pick up the options as if defined 
# by the kernel's .config. */
#
# XXX: move to a C dialog, also, there's gotta be a quicker, shorter
# way to do this too... meh?
#
# Only enable defines we really need.
export

# Wireless subsystem stuff
CONFIG_MAC80211=m
ifeq ($(CONFIG_MAC80211),m)
COPTS+= -DCONFIG_MAC80211=1
endif

CONFIG_MAC80211_RCSIMPLE=y
ifeq ($(CONFIG_MAC80211_RCSIMPLE),y)
COPTS+= -DCONFIG_MAC80211_RCSIMPLE=1
endif

CONFIG_CFG80211=m
ifeq ($(CONFIG_CFG80211),m)
COPTS+= -DCONFIG_CFG80211=1
endif

CONFIG_NL80211=y
ifeq ($(CONFIG_NL80211),y)
COPTS+= -DCONFIG_NL80211=1
endif

# Drivers
CONFIG_ATH5K=m
ifeq ($(CONFIG_ATH5K),m)
#COPTS+= -DCONFIG_ATH5K=1
endif

CONFIG_IWL3945=m
ifeq ($(CONFIG_IWL3945),m)
#COPTS+= -DCONFIG_IWL3945=1
endif

CONFIG_IWL4965=m
ifeq ($(CONFIG_IWL4965),m)
#COPTS+= -DCONFIG_IWL4965=1
endif

CONFIG_ZD1211RW=m
ifeq ($(CONFIG_ZD1211RW),m)
#COPTS+= -DCONFIG_ZD1211RW=1
endif
# CONFIG_ZD1211RW_MAC80211_DEBUG is not set

CONFIG_B43=m
ifeq ($(CONFIG_B43),m)
#COPTS+= -DCONFIG_B43=1
endif

# B43 uses PCMCIA only for Compact Flash. The Cardbus cards uses PCI
# Example, bcm4318:
# http://www.multicap.biz/wireless-lan/indoor-wlan-hardware/sdc-cf10g-80211g-compact-flash-module
CONFIG_B43_PCMCIA=y
ifeq ($(CONFIG_B43_PCMCIA),y)
COPTS+= -DCONFIG_B43_PCMCIA=1
endif

CONFIG_B43_DMA=y
ifeq ($(CONFIG_B43_DMA),y)
COPTS+= -DCONFIG_B43_DMA=1
endif

CONFIG_B43_PIO=y
ifeq ($(CONFIG_B43_PIO),y)
COPTS+= -DCONFIG_B43_PIO=1
endif

CONFIG_B43_DMA_AND_PIO_MODE=y
ifeq ($(CONFIG_B43_DMA_AND_PIO_MODE),y)
COPTS+= -DCONFIG_B43_DMA_AND_PIO_MODE=1
endif

CONFIG_B43_PCI_AUTOSELECT=y
ifeq ($(CONFIG_B43_PCI_AUTOSELECT),y)
COPTS+= -DCONFIG_B43_PCI_AUTOSELECT=1
endif

CONFIG_B43_PCICORE_AUTOSELECT=y
ifeq ($(CONFIG_B43_PCICORE_AUTOSELECT),y)
COPTS+= -DCONFIG_B43_PCICORE_AUTOSELECT=1
endif

#CONFIG_B43_RFKILL=n
#CONFIG_B43_LEDS=n
# CONFIG_B43_DEBUG is not set

CONFIG_B43LEGACY=m
ifeq ($(CONFIG_B43LEGACY),m)
#COPTS+= -DCONFIG_B43LEGACY=1
endif

CONFIG_B43LEGACY_PCI_AUTOSELECT=y
ifeq ($(CONFIG_B43LEGACY_PCI_AUTOSELECT),y)
COPTS+= -DCONFIG_B43LEGACY_PCI_AUTOSELECT=1
endif

CONFIG_B43LEGACY_PCICORE_AUTOSELECT=y
ifeq ($(CONFIG_B43LEGACY_PCICORE_AUTOSELECT),y)
COPTS+= -DCONFIG_B43LEGACY_PCICORE_AUTOSELECT=1
endif

CONFIG_B43LEGACY_DMA=y
ifeq ($(CONFIG_B43LEGACY_DMA),y)
COPTS+= -DCONFIG_B43LEGACY_DMA=1
endif

CONFIG_B43LEGACY_PIO=y
ifeq ($(CONFIG_B43LEGACY_PIO),y)
COPTS+= -DCONFIG_B43LEGACY_PIO=1
endif

CONFIG_B43LEGACY_DMA_AND_PIO_MODE=y
ifeq ($(CONFIG_B43LEGACY_DMA_AND_PIO_MODE),y)
COPTS+= -DCONFIG_B43LEGACY_DMA_AND_PIO_MODE=1
endif

# This is required for some cards
CONFIG_EEPROM_93CX6=m
ifeq ($(CONFIG_EEPROM_93CX6),m)
#COPTS+= -DCONFIG_EEPROM_93CX6=1
endif

# Realtek
CONFIG_RTL8180=m
ifeq ($(CONFIG_RTL8180),m)
#COPTS+= -DCONFIG_RTL8180=1
endif

CONFIG_RTL8187=m
ifeq ($(CONFIG_RTL8187),m)
#COPTS+= -DCONFIG_RTL8187=1
endif

CONFIG_ADM8211=m
ifeq ($(CONFIG_ADM8211),m)
#COPTS+= -DCONFIG_ADM8211=1
endif

# rt2x00
CONFIG_RT2X00=m
ifeq ($(CONFIG_RT2X00),m)
#COPTS+= -DCONFIG_RT2X00=1
endif

CONFIG_RT2X00_LIB=m
ifeq ($(CONFIG_RT2X00_LIB),m)
#COPTS+= -DCONFIG_RT2X00_LIB=1
endif

CONFIG_RT2X00_LIB_PCI=m
ifeq ($(CONFIG_RT2X00_LIB_PCI),m)
#COPTS+= -DCONFIG_RT2X00_LIB_PCI=1
endif

CONFIG_RT2X00_LIB_USB=m
ifeq ($(CONFIG_RT2X00_LIB_USB),m)
#COPTS+= -DCONFIG_RT2X00_LIB_USB=1
endif

CONFIG_RT2X00_LIB_FIRMWARE=y
ifeq ($(CONFIG_RT2X00_LIB_FIRMWARE),y)
COPTS+= -DCONFIG_RT2X00_LIB_FIRMWARE=1
endif

CONFIG_RT2400PCI=m
ifeq ($(CONFIG_RT2400PCI),m)
#COPTS+= -DCONFIG_RT2400PCI=1
endif

# CONFIG_RT2400PCI_RFKILL is not set
CONFIG_RT2500PCI=m
ifeq ($(CONFIG_RT2500PCI),m)
#COPTS+= -DCONFIG_RT2500PCI=1
endif

# CONFIG_RT2500PCI_RFKILL is not set
CONFIG_RT61PCI=m
ifeq ($(CONFIG_RT61PCI),m)
#COPTS+= -DCONFIG_RT61PCI=1
endif

# CONFIG_RT61PCI_RFKILL is not set
CONFIG_RT2500USB=m
ifeq ($(CONFIG_RT2500USB),m)
#COPTS+= -DCONFIG_RT2500USB=1
endif

CONFIG_RT73USB=m
ifeq ($(CONFIG_RT73USB),m)
#COPTS+= -DCONFIG_RT73USB=1
endif
# CONFIG_RT2X00_LIB_DEBUGFS is not set
# CONFIG_RT2X00_DEBUG is not se

# p54
CONFIG_P54_COMMON=m
ifeq ($(CONFIG_P54_COMMON),m)
#COPTS+= -DCONFIG_P54_COMMON=1
endif

CONFIG_P54_USB=m
ifeq ($(CONFIG_P54_USB),m)
#COPTS+= -DCONFIG_P54_USB=1
endif

CONFIG_P54_PCI=m
ifeq ($(CONFIG_P54_PCI),m)
#COPTS+= -DCONFIG_P54_PCI=1
endif

# Sonics Silicon Backplane
CONFIG_SSB_POSSIBLE=y
ifeq ($(CONFIG_SSB_POSSIBLE),y)
#COPTS+= -DCONFIG_SSB_POSSIBLE=1
endif

CONFIG_SSB=m
ifeq ($(CONFIG_SSB),m)
#COPTS+= -DCONFIG_SSB=1
endif

CONFIG_SSB_PCIHOST_POSSIBLE=y
ifeq ($(CONFIG_SSB_PCIHOST_POSSIBLE),y)
COPTS+= -DCONFIG_SSB_PCIHOST_POSSIBLE=1
endif

CONFIG_SSB_PCIHOST=y
ifeq ($(CONFIG_SSB_PCIHOST),y)
COPTS+= -DCONFIG_SSB_PCIHOST=1
endif

CONFIG_SSB_PCMCIAHOST=y
ifeq ($(CONFIG_SSB_PCMCIAHOST),y)
COPTS+= -DCONFIG_SSB_PCMCIAHOST=1
endif

CONFIG_SSB_DRIVER_PCICORE_POSSIBLE=y
ifeq ($(CONFIG_SSB_DRIVER_PCICORE_POSSIBLE),y)
#COPTS+= -DCONFIG_SSB_DRIVER_PCICORE_POSSIBLE=1
endif

CONFIG_SSB_DRIVER_PCICORE=y
ifeq ($(CONFIG_SSB_DRIVER_PCICORE),y)
COPTS+= -DCONFIG_SSB_DRIVER_PCICORE=1
endif

ifeq ($(CONFIG_SSB_PCIHOST),y)
COPTS+= -DCONFIG_SSB_PCIHOST=1
endif

# These two are for mips
CONFIG_SSB_DRIVER_MIPS=n
CONFIG_SSB_PCICORE_HOSTMODE=n
# CONFIG_SSB_DEBUG is not set
# CONFIG_SSB_DRIVER_EXTIF=y

# Old ieee80211 "stack"
# Note: old softmac is scheduled for removal so we
# ignore that stuff
CONFIG_IEEE80211=m
ifeq ($(CONFIG_IEEE80211),m)
#COPTS+= -DCONFIG_IEEE80211=1
endif

CONFIG_IEEE80211_CRYPT_CCMP=m
ifeq ($(CONFIG_IEEE80211_CRYPT_CCMP),m)
#COPTS+= -DCONFIG_IEEE80211_CRYPT_CCMP=1
endif

CONFIG_IEEE80211_CRYPT_TKIP=m
ifeq ($(CONFIG_IEEE80211_CRYPT_TKIP),m)
#COPTS+= -DCONFIG_IEEE80211_CRYPT_TKIP=1
endif

CONFIG_IEEE80211_CRYPT_WEP=m
ifeq ($(CONFIG_IEEE80211_CRYPT_WEP),m)
#COPTS+= -DCONFIG_IEEE80211_CRYPT_WEP=1
endif

CONFIG_IEEE80211_SOFTMAC=n
# Old drivers which use the old stack

# The Intel ipws
CONFIG_IPW2100=m
ifeq ($(CONFIG_IPW2100),m)
#COPTS+= -DCONFIG_IPW2100=1
endif

CONFIG_IPW2200=m
ifeq ($(CONFIG_IPW2200),m)
#COPTS+= -DCONFIG_IPW2200=1
endif

# Libertas uses the old stack but not fully, it will soon 
# be cleaned.
CONFIG_LIBERTAS=m
ifeq ($(CONFIG_LIBERTAS),m)
#COPTS+= -DCONFIG_LIBERTAS=1
endif

CONFIG_LIBERTAS_USB=m
ifeq ($(CONFIG_LIBERTAS_USB),m)
#COPTS+= -DCONFIG_LIBERTAS_USB=1
endif

CONFIG_LIBERTAS_CS=m
ifeq ($(CONFIG_LIBERTAS_CS),m)
#COPTS+= -DCONFIG_LIBERTAS_CS=1
endif
