libertas-objs := main.o wext.o rx.o tx.o cmd.o cmdresp.o scan.o 11d.o	\
		 debugfs.o persistcfg.o ethtool.o assoc.o

sd8xxx-objs += if_sdio.o

obj-$(CONFIG_LIBERTAS)     += libertas.o
obj-$(CONFIG_LIBERTAS_SDIO) += sd8xxx.o
